# Generated by Django 5.2.1 on 2025-05-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preferred_competencies',
            field=models.TextField(blank=True, help_text='Enter the preferred competencies for this project, one per line.'),
        ),
    ]
