# Generated by Django 5.2.1 on 2025-05-26 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_preferred_competencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='update_text',
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='how_project_is_going',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='setbacks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='what_was_done',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
