# Generated by Django 5.2.1 on 2025-05-26 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectupdate_update_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='testers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'collaborator'}, related_name='projects_as_tester', to=settings.AUTH_USER_MODEL),
        ),
    ]
