# Generated by Django 5.2.1 on 2025-05-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='proficiency_level',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='best_competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_users', to='users.competency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles_preferred',
            field=models.CharField(blank=True, help_text='Comma separated list of preferred roles', max_length=255),
        ),
    ]
