# Generated by Django 5.2.1 on 2025-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_competency_proficiency_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='proficiency_level',
        ),
        migrations.AlterField(
            model_name='user',
            name='roles_preferred',
            field=models.CharField(blank=True, help_text='Comma separated list of preferred roles', max_length=255, null=True),
        ),
    ]
