# Generated by Django 5.2.1 on 2025-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_competency_proficiency_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('team_leader', 'Team Leader'), ('collaborator', 'Collaborator'), ('external_po', 'External PO')], max_length=20),
        ),
    ]
