# Generated by Django 5.2 on 2025-04-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('perna', models.CharField(max_length=1)),
                ('conquistas', models.TextField()),
                ('overall', models.DecimalField(decimal_places=2, max_digits=3)),
                ('selecaodoseculo', models.BooleanField(default=True)),
            ],
        ),
    ]
