# Generated by Django 5.2 on 2025-04-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('hard_skils', models.CharField(max_length=300)),
                ('soft_skils', models.CharField(max_length=300)),
                ('ex_developer', models.BooleanField(default=False)),
                ('ex_product_owner', models.BooleanField(default=False)),
                ('ex_scrum_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
