# Generated by Django 5.2 on 2025-05-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersapp', '0003_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='equipes', to='playersapp.funcionario'),
        ),
    ]
