# Generated by Django 5.2.1 on 2025-05-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersapp', '0005_funcionario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='playersapp.funcionario')),
            ],
        ),
    ]
