# Generated by Django 5.2 on 2025-05-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersapp', '0007_team_projeto_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='colaboradores',
            field=models.ManyToManyField(related_name='equipes', to='playersapp.funcionario'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to='playersapp.funcionario'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
