# Generated by Django 5.2 on 2025-05-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersapp', '0008_funcionario_foto_alter_equipe_colaboradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
